aws_region     = "us-east-1"
aws_profile    = "default"
instance_type  = "t2.micro"
ssh_key_name   = "wp-key"
db_name        = "wordpress"
db_username    = "wpadmin"
db_password    = "changeme123"
